# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1092, 799)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(0, 0, 113, 22))
        self.name.setObjectName("name")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(210, 0, 95, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(210, 20, 95, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 0, 93, 41))
        self.pushButton.setObjectName("pushButton")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(310, 0, 194, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.amounts = QtWidgets.QLineEdit(self.centralwidget)
        self.amounts.setGeometry(QtCore.QRect(0, 20, 113, 22))
        self.amounts.setObjectName("amounts")
        self.removename = QtWidgets.QLineEdit(self.centralwidget)
        self.removename.setGeometry(QtCore.QRect(970, 0, 113, 22))
        self.removename.setObjectName("removename")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(870, 0, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.income = QtWidgets.QListView(self.centralwidget)
        self.income.setGeometry(QtCore.QRect(0, 60, 256, 711))
        self.income.setObjectName("income")
        self.expenses = QtWidgets.QListView(self.centralwidget)
        self.expenses.setGeometry(QtCore.QRect(250, 60, 256, 711))
        self.expenses.setObjectName("expenses")
        self.total = QtWidgets.QListWidget(self.centralwidget)
        self.total.setGeometry(QtCore.QRect(930, 60, 161, 711))
        self.total.setObjectName("total")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1092, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton.setText(_translate("MainWindow", "income"))
        self.radioButton_2.setText(_translate("MainWindow", "expense"))
        self.pushButton.setText(_translate("MainWindow", "submit"))
        self.pushButton_2.setText(_translate("MainWindow", "remove"))
